baseURL = "/"
title = "Embrace Change"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 10
theme = "mainroad"
canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true
metaDataFormat = "toml"
paginatePath = "page"
googleAnalytics = "UA-136788356-1"

[frontmatter]
date = ["date"]

[author]
name = "Frank Mueller"
bio = "Frank Mueller / Oldenburg / Germany / Europe / World"
avatar = "/img/mue.jpg"

[params]
description = "Insights into the world of Frank Mueller"
opengraph = true
leftsidebar = false
authorbox = false
readmore = true
post_nagivation = true
date_format = "2006-01-02"
highlightColor = "#2e8b57"
post_meta = ["author", "date", "categories"]

[params.logo]
title = "Frank Mueller"
subtitle = "Change is the only Constant in Nature"

[params.sidebar]
home = "right"
list = "right"
single = false
widgets = ["search", "recent", "categories", "taglist"]

[params.widgets]
recent_num = 10
tags_counter = true

[permalinks]
post = "/blog/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"
