baseURL = "/"
title = "Embrace Change, Shape the Future"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 10
theme = "mainroad"
canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true
metaDataFormat = "toml"
paginatePath = "page"
cleanDestinationDir = false # TODO: Check destination cleaning.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
	date = ["date"]

[params]
	description = "Insights into the world of Frank Müller"
	copyright = "Frank Mueller"
	opengraph = true
	schema = true
	readmore = true
	paper = true
	site_logo = "/img/themue.svg"
	favicon = ""
	homepageLength = 10
	disableDarkModeCSS = true
	mathjax = true
	date_format = "2006-01-02"
	post_meta = ["author", "date", "categories"]
	customCSS = []

[params.logo]
	image = "img/themue.svg"
	title = "Embrace Change, Shape the Future"
	subtitle = "Insights into the World of Frank 'themue' Mueller"

[params.style.vars]
	highlightColor = "#449944"

[params.sidebar]
	home = "right"
	list = "right"
	single = true
	widgets = ["search", "recent", "categories", "taglist"]

[params.widgets]
	recent_num = 5
	categories_counter = true
	tags_counter = true

[permalinks]
	[permalinks.page]
    	posts = '/posts/:year/:month/:day/:slug/'
    	tutorials = '/tutorials/:slug/'
	[permalinks.section]
		posts = '/posts/'
    	tutorials = '/tutorials/'

[taxonomies]
	tag = "tags"
	category = "categories"
