baseURL = "/"
title = "Embrace Change"
languageCode = "en-us"
paginate = 10
theme = "mainroad"
canonifyURLs = true
enableEmoji = true
metaDataFormat = "toml"
paginatePath = "page"
googleAnalytics = "UA-136788356-1"

[author]
name = "Frank Mueller"
bio = "Frank Mueller / Oldenburg / Germany / Europe / World"
avatar = "/img/mue.jpg"

[params]
subtitle = "Insights into the world of Frank Mueller ..."
description = ""
opengraph = true
leftsidebar = false
authorbox = false
post_nagivation = true

[params.widgets]
search = true
recent_articles = true
recent_articles_num = 10
categories = true
tags = true
tags_counter = true

[permalinks]
post = "/blog/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"
