baseURL = "/"
title = "Embrace Change, Shape the Future"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 10
theme = "hugo-kiera"
canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true
metaDataFormat = "toml"
paginatePath = "page"

[frontmatter]
	date = ["date"]

[author]
	name = "Frank Mueller"
	bio = "Frank Mueller / Oldenburg / Germany / Europe / World"

[params]
	description = "Insights into the world of Frank Müller"
	customCSS = ["css/hugo-kiera-custom.css"]
	site_logo = "/img/highland-cow.jpg"
	# favicon = ""
	homepageLength = 10
	disableDarkModeCSS = true
	# commentAutoload = true  #This mean reader don't need click, disqus comment autoload
	# mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
	katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
	google_fonts = ["Staatliches"] # Adds additional google fonts
	date_format = "2006-01-02"
	post_meta = ["author", "date", "categories"]

[permalinks]
	[permalinks.page]
    	posts = '/posts/:year/:month/:day/:slug/'
    	tutorials = '/tutorials/:slug/'
	[permalinks.section]
		posts = '/posts/'
    	tutorials = '/tutorials/'

[[menu.main]]
	identifier = "categories"
	name = "Categories"
	url = "/categories"
	weight = 10

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags"
	weight = 20
