baseURL = "/"
languageCode = "en-us"
paginate = 10
theme = "mainroad"
canonifyURLs = true
enableEmoji = true
metaDataFormat = "toml"
paginatePath = "page"
googleAnalytics = "UA-136788356-1"

[author]
name = "Frank Mueller"
bio = "Frank Mueller / Oldenburg / Germany / Europe / World"
avatar = "/img/mue.jpg"

[params]
description = "Insights into the world of Frank Mueller ..."
opengraph = true
leftsidebar = false
authorbox = false
post_nagivation = true
date_format = "2006-01-02"
highlightColor = "#0000aa"

[params.logo]
title = "Embrace Change"
subtitle = "Insights into the world of Frank Mueller ..."

[params.sidebar]
home = "right"
list = "right"
single = false
widgets = ["search", "recent", "categories", "taglist"]

[params.widgets]
recent_num = 10
tags_counter = true

[permalinks]
post = "/blog/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"
