name = "themue"
license = "GPLv2"
description = "Hugo theme."
tags = ["blog", "responsive", "light", "customizable", "widgets"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "google analytics"]
min_version = "0.48"

[author]
  name = "themue"
  homepage = "https://github.com/themue"

