name = "themue"
license = "BSDv3"
licenseLink = "https://github.com/themue/site.themue.dev/"
description = "TheMue is based on MH Magazine Lite."
homepage = "https://github.com/themue/site.themue.dev/"
tags = ["blog", "responsive", "widgets", "rss", "disqus"]
features = ["blog", "responsive", "widgets", "rss", "disqus"]
min_version = 0.19

[author]
name = "themue"
homepage = "https://github.com/themue"
